GET http://localhost:3000/tweets

###
POST http://localhost:3000/tweets
Content-Type: application/json

{
    "Text": "Nestjs é muito show.....",
    "User": {
        "Name": "Matheus Santos"
    }
}

###
GET http://localhost:3000/mail-list

###
POST http://localhost:3000/mail-list
Content-Type: application/json

{
    "emails": [
        "user@test.com",
        "user2@test.com",
        "user3@test.com"
    ]
}